using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using Debug = UnityEngine.Debug;

namespace Fiftytwo
{
    public class GitInit : EditorWindow
    {
        private const string git = "git";

        private string _origin;
        private bool _withLFS;

        [MenuItem( "Window/Fiftytwo/Initialize Git" )]
        private static void ShowWindowMenuItem ()
        {
            var window = GetWindow<GitInit>( false );
            window.Show();
        }

        private void OnEnable ()
        {
            titleContent = new GUIContent( "Initialize Git" );
        }

        private void OnDisable ()
        {
        }

        private void OnGUI ()
        {
            GUILayout.Label( "Initialize Git" );

            _origin = GUILayout.TextField( _origin );
            _withLFS = GUILayout.Toggle( _withLFS, "With LFS" );

            if( GUILayout.Button( "Init" ) )
            {
                var path = Environment.GetEnvironmentVariable( "PATH" );
                if( !path.Contains( "/usr/local/bin" ) )
                {
                    path = "/usr/local/bin:" + path;
                    Environment.SetEnvironmentVariable( "PATH", path );
                }

                //ExecuteProcess( "bash", "-c env" );
                //return;

                ExecuteProcess( git, "init" );

                if( _withLFS )
                    ExecuteProcess( "git", "lfs install" );

                if( !string.IsNullOrEmpty( _origin ) )
                {
                    ExecuteProcess( git, "remote rm origin", true );
                    ExecuteProcess( git, "remote add origin " + _origin );
                    ExecuteProcess( git, "fetch --all" );
                    ExecuteProcess( git, "reset --hard origin/master" );
                    ExecuteProcess( git, "pull origin master" );
                    ExecuteProcess( git, "branch -u origin/master" );
                }

                Debug.Log( "Generate .gitignore" );
                File.WriteAllText( ".gitignore", gitignore );
                Debug.Log( "Generate .gitattributes" );
                File.WriteAllText( ".gitattributes", gitattributes );
            }
        }

        private static int ExecuteProcess ( string executablePath, string arguments, bool suppressLog = false )
        {
            string output;
            string error;

            var code = ExecuteProcess( executablePath, arguments, out output, out error );

            if( !suppressLog )
            {
                var message = new StringBuilder( executablePath );
                message.Append( " " );
                message.AppendLine( arguments );
                message.Append( "Completed with code " );
                message.Append( code );
                if( !string.IsNullOrEmpty( output ) )
                {
                    message.AppendLine();
                    message.Append( output );
                }
                if( !string.IsNullOrEmpty( error ) )
                {
                    message.AppendLine();
                    message.Append( error );
                }

                if( code == 0 )
                    Debug.Log( message.ToString() );
                else
                    Debug.LogError( message.ToString() );
            }

            return code;
        }

        private static int ExecuteProcess ( string executablePath, string arguments, out string output, out string error )
        {
            ProcessStartInfo startInfo = new ProcessStartInfo( executablePath );
            startInfo.Arguments = arguments;
            startInfo.UseShellExecute = false;
            startInfo.RedirectStandardOutput = true;
            startInfo.RedirectStandardError = true;

            Process process = Process.Start( startInfo );

            output = process.StandardOutput.ReadToEnd();
            error = process.StandardError.ReadToEnd();

            process.WaitForExit();

            return process.ExitCode;
        }

        private const string gitignore = @"# OS generated trash
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
[Ee]hthumbs.db
[Tt]humbs.db

/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/Assets/AssetStoreTools*

# Visual Studio 2015 cache directory
/.vs/

# Autogenerated VS/MD/Consulo solution and project files
/*.csproj
/*.unityproj
/*.sln
/*.booproj
ExportedObj/
ExportedObj.meta
Bin/
Bin.meta
Debug/
Debug.meta
Release/
Release.meta
.consulo/
.consulo.meta
*.suo
*.suo.meta
*.tmp
*.tmp.meta
*.user
*.user.meta
*.userprefs
*.userprefs.meta
*.pidb
*.pidb.meta
*.svd
*.svd.meta
*.pdb
*.pdb.meta
*.dSYM
*.dSYM.meta
*.exe.stackdump
*.exe.stackdump.meta
*.sln.docstates
*.sln.docstates.meta

# Unity3D Generated File On Crash Reports
sysinfo.txt

# VS Code
.vscode/launch.json
.vscode/.*

# NUnit test results
/Assets/test-results
/Assets/test-results.meta

# Xcode
xcuserdata/
*.xccheckout

# Generated assets
/Assets/Generated.meta
/Assets/Generated/
";

        private const string gitattributes = @"## Wildcard templates
#
## macOS binaries
/**/*.bundle/Contents/MacOS/* filter=lfs diff=lfs merge=lfs -text
/**/*.app/Contents/MacOS/* filter=lfs diff=lfs merge=lfs -text
#
## Unity code
*.cs diff=csharp text
*.shader text
*.cginc text
*.compute text
#
## Unity YAML
# Remove lfs specific attributes from *.meta because wildcard template can set them
*.meta !filter !diff !text linguist-generated merge=unityyamlmerge eol=lf
*.mat linguist-generated merge=unityyamlmerge eol=lf
*.anim linguist-generated merge=unityyamlmerge eol=lf
*.unity linguist-generated merge=unityyamlmerge eol=lf
*.prefab linguist-generated merge=unityyamlmerge eol=lf
*.physicMaterial2D linguist-generated merge=unityyamlmerge eol=lf
*.physicMaterial linguist-generated merge=unityyamlmerge eol=lf
*.asset linguist-generated merge=unityyamlmerge eol=lf
*.controller linguist-generated merge=unityyamlmerge eol=lf
*.playable linguist-generated merge=unityyamlmerge eol=lf
*.giparams linguist-generated merge=unityyamlmerge eol=lf
#
## Unity LFS
*.cubemap filter=lfs diff=lfs merge=lfs -text
*.CUBEMAP filter=lfs diff=lfs merge=lfs -text
*.unitypackage filter=lfs diff=lfs merge=lfs -text
*.UNITYPACKAGE filter=lfs diff=lfs merge=lfs -text
#
## 3D models
*.3dm filter=lfs diff=lfs merge=lfs -text
*.3DM filter=lfs diff=lfs merge=lfs -text
*.3ds filter=lfs diff=lfs merge=lfs -text
*.3DS filter=lfs diff=lfs merge=lfs -text
*.blend filter=lfs diff=lfs merge=lfs -text
*.BLEND filter=lfs diff=lfs merge=lfs -text
*.c4d filter=lfs diff=lfs merge=lfs -text
*.C4D filter=lfs diff=lfs merge=lfs -text
*.collada filter=lfs diff=lfs merge=lfs -text
*.COLLADA filter=lfs diff=lfs merge=lfs -text
*.dae filter=lfs diff=lfs merge=lfs -text
*.DAE filter=lfs diff=lfs merge=lfs -text
*.dxf filter=lfs diff=lfs merge=lfs -text
*.DXF filter=lfs diff=lfs merge=lfs -text
*.fbx filter=lfs diff=lfs merge=lfs -text
*.FBX filter=lfs diff=lfs merge=lfs -text
*.jas filter=lfs diff=lfs merge=lfs -text
*.JAS filter=lfs diff=lfs merge=lfs -text
*.lws filter=lfs diff=lfs merge=lfs -text
*.LWS filter=lfs diff=lfs merge=lfs -text
*.lxo filter=lfs diff=lfs merge=lfs -text
*.LXO filter=lfs diff=lfs merge=lfs -text
*.ma filter=lfs diff=lfs merge=lfs -text
*.MA filter=lfs diff=lfs merge=lfs -text
*.max filter=lfs diff=lfs merge=lfs -text
*.MAX filter=lfs diff=lfs merge=lfs -text
*.mb filter=lfs diff=lfs merge=lfs -text
*.MB filter=lfs diff=lfs merge=lfs -text
*.obj filter=lfs diff=lfs merge=lfs -text
*.OBJ filter=lfs diff=lfs merge=lfs -text
*.ply filter=lfs diff=lfs merge=lfs -text
*.PLY filter=lfs diff=lfs merge=lfs -text
*.skp filter=lfs diff=lfs merge=lfs -text
*.SKP filter=lfs diff=lfs merge=lfs -text
*.stl filter=lfs diff=lfs merge=lfs -text
*.STL filter=lfs diff=lfs merge=lfs -text
*.ztl filter=lfs diff=lfs merge=lfs -text
*.ZTL filter=lfs diff=lfs merge=lfs -text
*.mesh filter=lfs diff=lfs merge=lfs -text
*.MESH filter=lfs diff=lfs merge=lfs -text
#
## Audio
*.aif filter=lfs diff=lfs merge=lfs -text
*.AIF filter=lfs diff=lfs merge=lfs -text
*.aiff filter=lfs diff=lfs merge=lfs -text
*.AIFF filter=lfs diff=lfs merge=lfs -text
*.it filter=lfs diff=lfs merge=lfs -text
*.IT filter=lfs diff=lfs merge=lfs -text
*.mod filter=lfs diff=lfs merge=lfs -text
*.MOD filter=lfs diff=lfs merge=lfs -text
*.mp3 filter=lfs diff=lfs merge=lfs -text
*.MP3 filter=lfs diff=lfs merge=lfs -text
*.ogg filter=lfs diff=lfs merge=lfs -text
*.OGG filter=lfs diff=lfs merge=lfs -text
*.s3m filter=lfs diff=lfs merge=lfs -text
*.S3M filter=lfs diff=lfs merge=lfs -text
*.wav filter=lfs diff=lfs merge=lfs -text
*.WAV filter=lfs diff=lfs merge=lfs -text
*.xm filter=lfs diff=lfs merge=lfs -text
*.XM filter=lfs diff=lfs merge=lfs -text
*.m4a filter=lfs diff=lfs merge=lfs -text
*.M4A filter=lfs diff=lfs merge=lfs -text
*.rns filter=lfs diff=lfs merge=lfs -text
*.RNS filter=lfs diff=lfs merge=lfs -text
*.reason filter=lfs diff=lfs merge=lfs -text
*.REASON filter=lfs diff=lfs merge=lfs -text
#
## Video
*.asf filter=lfs diff=lfs merge=lfs -text
*.ASF filter=lfs diff=lfs merge=lfs -text
*.avi filter=lfs diff=lfs merge=lfs -text
*.AVI filter=lfs diff=lfs merge=lfs -text
*.flv filter=lfs diff=lfs merge=lfs -text
*.FLV filter=lfs diff=lfs merge=lfs -text
*.mov filter=lfs diff=lfs merge=lfs -text
*.MOV filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text
*.MP4 filter=lfs diff=lfs merge=lfs -text
*.mpeg filter=lfs diff=lfs merge=lfs -text
*.MPEG filter=lfs diff=lfs merge=lfs -text
*.mpg filter=lfs diff=lfs merge=lfs -text
*.MPG filter=lfs diff=lfs merge=lfs -text
*.ogv filter=lfs diff=lfs merge=lfs -text
*.OGV filter=lfs diff=lfs merge=lfs -text
*.wmv filter=lfs diff=lfs merge=lfs -text
*.WMV filter=lfs diff=lfs merge=lfs -text
#
## Images
*.bmp filter=lfs diff=lfs merge=lfs -text
*.BMP filter=lfs diff=lfs merge=lfs -text
*.exr filter=lfs diff=lfs merge=lfs -text
*.EXR filter=lfs diff=lfs merge=lfs -text
*.gif filter=lfs diff=lfs merge=lfs -text
*.GIF filter=lfs diff=lfs merge=lfs -text
*.hdr filter=lfs diff=lfs merge=lfs -text
*.HDR filter=lfs diff=lfs merge=lfs -text
*.iff filter=lfs diff=lfs merge=lfs -text
*.IFF filter=lfs diff=lfs merge=lfs -text
*.jpeg filter=lfs diff=lfs merge=lfs -text
*.JPEG filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
*.JPG filter=lfs diff=lfs merge=lfs -text
*.pict filter=lfs diff=lfs merge=lfs -text
*.PICT filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
*.PNG filter=lfs diff=lfs merge=lfs -text
*.apng filter=lfs diff=lfs merge=lfs -text
*.APNG filter=lfs diff=lfs merge=lfs -text
*.psd filter=lfs diff=lfs merge=lfs -text
*.PSD filter=lfs diff=lfs merge=lfs -text
*.tga filter=lfs diff=lfs merge=lfs -text
*.TGA filter=lfs diff=lfs merge=lfs -text
*.tif filter=lfs diff=lfs merge=lfs -text
*.TIF filter=lfs diff=lfs merge=lfs -text
*.tiff filter=lfs diff=lfs merge=lfs -text
*.TIFF filter=lfs diff=lfs merge=lfs -text
#
## Compressed Archive
*.7z filter=lfs diff=lfs merge=lfs -text
*.7Z filter=lfs diff=lfs merge=lfs -text
*.bz2 filter=lfs diff=lfs merge=lfs -text
*.BZ2 filter=lfs diff=lfs merge=lfs -text
*.gz filter=lfs diff=lfs merge=lfs -text
*.GZ filter=lfs diff=lfs merge=lfs -text
*.rar filter=lfs diff=lfs merge=lfs -text
*.RAR filter=lfs diff=lfs merge=lfs -text
*.tar filter=lfs diff=lfs merge=lfs -text
*.TAR filter=lfs diff=lfs merge=lfs -text
*.zip filter=lfs diff=lfs merge=lfs -text
*.ZIP filter=lfs diff=lfs merge=lfs -text
#
## Compiled code
*.dll filter=lfs diff=lfs merge=lfs -text
*.DLL filter=lfs diff=lfs merge=lfs -text
*.pdb filter=lfs diff=lfs merge=lfs -text
*.PDB filter=lfs diff=lfs merge=lfs -text
*.so filter=lfs diff=lfs merge=lfs -text
*.SO filter=lfs diff=lfs merge=lfs -text
*.a filter=lfs diff=lfs merge=lfs -text
*.A filter=lfs diff=lfs merge=lfs -text
*.dylib filter=lfs diff=lfs merge=lfs -text
*.DYLIB filter=lfs diff=lfs merge=lfs -text
*.apk filter=lfs diff=lfs merge=lfs -text
*.APK filter=lfs diff=lfs merge=lfs -text
*.exe filter=lfs diff=lfs merge=lfs -text
*.EXE filter=lfs diff=lfs merge=lfs -text
*.jar filter=lfs diff=lfs merge=lfs -text
*.JAR filter=lfs diff=lfs merge=lfs -text
*.war filter=lfs diff=lfs merge=lfs -text
*.WAR filter=lfs diff=lfs merge=lfs -text
*.WAR filter=lfs diff=lfs merge=lfs -text
#
## Fonts
*.otf filter=lfs diff=lfs merge=lfs -text
*.OTF filter=lfs diff=lfs merge=lfs -text
*.ttf filter=lfs diff=lfs merge=lfs -text
*.TTF filter=lfs diff=lfs merge=lfs -text
#
## Documents
*.pdf filter=lfs diff=lfs merge=lfs -text
*.PDF filter=lfs diff=lfs merge=lfs -text
*.doc filter=lfs diff=lfs merge=lfs -text
*.DOC filter=lfs diff=lfs merge=lfs -text
*.docx filter=lfs diff=lfs merge=lfs -text
*.DOCX filter=lfs diff=lfs merge=lfs -text
*.chm filter=lfs diff=lfs merge=lfs -text
*.CHM filter=lfs diff=lfs merge=lfs -text
#
";
    }
}
